context:
  version: 2.0.0
  build_number: 0

package:
  name: bws
  version: ${{ version }}

source:
  - url: https://github.com/bitwarden/sdk-sm/archive/refs/tags/bws-v${{ version }}.tar.gz
    sha256: 60ab649d847a3e7d3529e87d2919dab010abcd5df3457aad1c50240cbd2e7162

build:
  number: ${{ build_number }}
  script:
    content:
      - ${BUILD_PREFIX}/bin/cargo auditable install --no-track
        --locked --path ${SRC_DIR}/crates/bws --root ${PREFIX}
      - install -dm0755 ${PREFIX}/share/bash-completion/completions
        ${PREFIX}/share/zsh/site-functions ${PREFIX}/share/fish/vendor_completions.d
      - ${PREFIX}/bin/bws completions bash > ${PREFIX}/share/bash-completion/completions/bws
      - ${PREFIX}/bin/bws completions fish > ${PREFIX}/share/fish/vendor_completions.d/bws.fish
      - ${PREFIX}/bin/bws completions zsh > ${PREFIX}/share/zsh/site-functions/_bws
      - ${BUILD_PREFIX}/bin/cargo-bundle-licenses --format=yaml --output=${SRC_DIR}/THIRDPARTY.yml
    env:
      ASSET_OUT_DIR: ${SRC_DIR}/target
      CARGO_PROFILE_RELEASE_LTO: thin
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_TARGET_DIR: ${SRC_DIR}/target

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses

tests:
  - package_contents:
      strict: true
      bin:
        - bws
      files:
        - share/bash-completion/completions/bws
        - share/fish/vendor_completions.d/bws.fish
        - share/zsh/site-functions/_bws
  - script:
      - bws --version

about:
  homepage: https://bitwarden.com/products/secrets-manager
  repository: https://github.com/bitwarden/sdk-sm
  documentation: https://bitwarden.com/help/secrets-manager-cli
  summary: The Bitwarden Secrets Manager CLI
  description: >-
    A Rust CLI for interacting with the Bitwarden Secrets Manager.
  license: |
    LicenseRef-BITWARDEN-SOFTWARE-DEVELOPMENT-KIT-LICENSE-AGREEMENT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
