context:
  version: 4.18.2
  build_number: 0

package:
  name: git-cola
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/g/git-cola/git_cola-${{ version }}.tar.gz
    sha256: f1f1d9ddd33e6d319d2612b496b39cbf6ea300e5be0f305e1b4ae779236c6662

build:
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - cola = cola.main:main
      - git-cola = cola.main:main
      - git-cola-sequence-editor = cola.sequenceeditor:main
      - git-dag = cola.dag:main
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
  run:
    - polib >=1.0.0
    - qtpy >=1.1.0
  # - pytest >=6 # extra == "testing"
  # - pytest-checkdocs >=2.4 # extra == "testing"
  # - pytest-enabler >=2.2 # extra == "testing"
  # - pytest-ruff >=0.2.1 # extra == "testing"
  # - furo  # extra == "docs"
  # - sphinx  # extra == "docs"
  # - rst.linker >=1.9 # extra == "docs"
  # - notify2  # extra == "extras"
  # - pyobjc  # sys_platform == "darwin" and extra == "extras"
  # - send2trash  # extra == "extras"
  # - cercis  # extra == "dev"
  # - mypy ==1.19.1 # extra == "dev"
  # - pyupgrade  # extra == "dev"
  # - build  # extra == "build"
  # - pynsist  # extra == "build"
  # - setuptools >=64.0 # extra == "build"
  # - setuptools_scm [toml]>=3.4.1 # extra == "build"
  # - twine  # extra == "build"
  # - wheel  # extra == "build"
  # - pyqt5  # extra == "pyqt5"
  # - pyqt6  # extra == "pyqt6"
  # - pyside2  # extra == "pyside2"
  # - pyside6  # extra == "pyside6"

tests:
  - package_contents:
      strict: true
      site_packages:
        - cola/*
        - git_cola-${{ version }}.dist-info/*

about:
  summary: The highly caffeinated Git GUI
  homepage: https://git-cola.gitlab.io
  repository: https://github.com/git-cola/git-cola.git
  description: >-
    Git Cola is a powerful Git GUI with a slick and intuitive user interface.
  license: GPL-2.0-only
  license_file:
    - LICENSE
